{% if drop_table %}
DROP TABLE IF EXISTS "{{ table_name }}";
{% endif %}

CREATE TABLE IF NOT EXISTS "{{ table_name }}" (
    "TimeStamp" TIMESTAMPTZ NOT NULL,
    "Delta_TP9" DOUBLE PRECISION, "Delta_AF7" DOUBLE PRECISION, "Delta_AF8" DOUBLE PRECISION, "Delta_TP10" DOUBLE PRECISION,
    "Theta_TP9" DOUBLE PRECISION, "Theta_AF7" DOUBLE PRECISION, "Theta_AF8" DOUBLE PRECISION, "Theta_TP10" DOUBLE PRECISION,
    "Alpha_TP9" DOUBLE PRECISION, "Alpha_AF7" DOUBLE PRECISION, "Alpha_AF8" DOUBLE PRECISION, "Alpha_TP10" DOUBLE PRECISION,
    "Beta_TP9" DOUBLE PRECISION, "Beta_AF7" DOUBLE PRECISION, "Beta_AF8" DOUBLE PRECISION, "Beta_TP10" DOUBLE PRECISION,
    "Gamma_TP9" DOUBLE PRECISION, "Gamma_AF7" DOUBLE PRECISION, "Gamma_AF8" DOUBLE PRECISION, "Gamma_TP10" DOUBLE PRECISION,
    "RAW_TP9" DOUBLE PRECISION, "RAW_AF7" DOUBLE PRECISION, "RAW_AF8" DOUBLE PRECISION, "RAW_TP10" DOUBLE PRECISION,
    "AUX_RIGHT" DOUBLE PRECISION, "AUX_LEFT" DOUBLE PRECISION,
    "Accelerometer_X" DOUBLE PRECISION, "Accelerometer_Y" DOUBLE PRECISION, "Accelerometer_Z" DOUBLE PRECISION,
    "Gyro_X" DOUBLE PRECISION, "Gyro_Y" DOUBLE PRECISION, "Gyro_Z" DOUBLE PRECISION,
    "PPG_Ambient" DOUBLE PRECISION, "PPG_IR" DOUBLE PRECISION, "PPG_Red" DOUBLE PRECISION,
    "Heart_Rate" DOUBLE PRECISION,
    "HeadBandOn" INTEGER,
    "HSI_TP9" DOUBLE PRECISION, "HSI_AF7" DOUBLE PRECISION, "HSI_AF8" DOUBLE PRECISION, "HSI_TP10" DOUBLE PRECISION,
    "Battery" DOUBLE PRECISION,
    "Elements" TEXT
);

SELECT create_hypertable(
    '{{ table_name }}',
    'TimeStamp',
    chunk_time_interval => INTERVAL '30 days',
    if_not_exists => TRUE
);
