services:
  grafana:
    image: grafana/grafana:12.4.8-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=motherduck-duckdb-datasource
      - GF_PLUGINS_PREINSTALL=motherduck-duckdb-datasource@@https://github.com/motherduckdb/grafana-duckdb-datasource/releases/download/v0.4.5/motherduck-duckdb-datasource-0.4.5.zip
    volumes:
      - ./data/eeg.duckdb:/var/lib/grafana/duckdb_data:ro
      - ./grafana-duckdb-datasource.yaml:/etc/grafana/provisioning/datasources/duckdb.yaml
      - grafana_storage:/var/lib/grafana

volumes:
  grafana_storage:
